### ISSUE TITLE
InsertDataSampleService

### ISSUE THREAD

**Issue by TheManoel** [Arquisoft/InciDashboard_i1a#4]
I will start entering new sample data to prove the dashboard. Although there is no data taken from kafka, this will help us to test that the dashboard works propertly.

**Comment by pedrytus** [comment]
The "first version" of the InsertDataSampleService is done. Now, a nice enhancement would be inserting random Incidents, since we have only 5 incidents created by hand and for good tests we should need like 50 Incidents more.

**Comment by pedrytus** [comment]
A more updated issue that talks about all this topic is [this one](https://github.com/Arquisoft/InciDashboard_i1a/issues/6).

**Comment by robertops18** [comment]
Creation updated
