### ISSUE TITLE
Incidents generated randomly

### ISSUE THREAD

**Issue by TheManoel** [Arquisoft/InciDashboard_i1a#6]
The code to generate random incidents has already been implemented. If someone wants to test it and purpose somo other functionalities related to this random generator.

**Comment by pedrytus** [comment]
I have cleaned the Java Class about 5 minutes ago in order to avoid unnecesary code-commented and obsolete method calls.

The rest seems to be fine, good job 👍

**Comment by robertops18** [comment]
I changed the creation in order to add the operator assigned to the incident and the location field, that now is a LatLng object, which stores latitude and longitude
